name: Branch push
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: Run tests
        run: |
          pytest tests/

  draft-release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      # Required to request the OIDC JWT Token
      id-token: write
      # Required when GH token is used to authenticate with private repo
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: KoblerS/release-drafter@v1
